import Cocoa
import CryptoKit

protocol PasteboardReadable {
    var changeCount: Int { get }
    var frontmostBundleId: String? { get }
    func stringValue() -> String?
    func imageData() -> Data?
    func isEmpty() -> Bool
    func fileURLs() -> [URL]?
    func hasMarkerType() -> Bool
    func hasIgnoredSystemType() -> Bool
}

final class NSPasteboardGateway: PasteboardReadable {
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    var changeCount: Int {
        NSPasteboard.general.changeCount
    }

    var frontmostBundleId: String? {
        NSWorkspace.shared.frontmostApplication?.bundleIdentifier
    }

    func stringValue() -> String? {
        NSPasteboard.general.string(forType: .string)
    }

    func imageData() -> Data? {
        NSPasteboard.general.data(forType: .tiff) ?? NSPasteboard.general.data(forType: .png)
    }

    func fileURLs() -> [URL]? {
        guard let urls = NSPasteboard.general.readObjects(forClasses: [NSURL.self], options: [
            .urlReadingFileURLsOnly: true,
        ]) as? [URL], !urls.isEmpty else { return nil }
        return urls
    }

    func isEmpty() -> Bool {
        guard let items = NSPasteboard.general.pasteboardItems, !items.isEmpty else { return true }
        return stringValue() == nil && imageData() == nil && fileURLs() == nil
    }

    func hasMarkerType() -> Bool {
        NSPasteboard.general.data(forType: ClipboardActionService.markerType) != nil
    }

    func hasIgnoredSystemType() -> Bool {
        let pb = NSPasteboard.general
        return pb.data(forType: Self.transientType) != nil
            || pb.data(forType: Self.autoGeneratedType) != nil
    }
}

enum ContentFingerprint {
    static func hash(text: String) -> String {
        guard let data = text.data(using: .utf8) else { return "" }
        return SHA256.hash(data: data).compactMap { String(format: "%02x", $0) }.joined()
    }

    static func hash(data: Data) -> String {
        SHA256.hash(data: data).compactMap { String(format: "%02x", $0) }.joined()
    }
}

final class ClipboardService {
    private let repository: ClipboardRepository
    private let settings: SettingsStore
    private let pasteboard: PasteboardReadable
    private let ruleEngine: ClipboardRuleEngine
    private var timer: Timer?
    private var lastChangeCount: Int = 0
    private let monitorInterval: TimeInterval
    private var lastInsertedUUID: UUID?

    init(
        repository: ClipboardRepository = CoreDataClipboardRepository(),
        settings: SettingsStore = UserDefaultsSettingsStore(),
        pasteboard: PasteboardReadable = NSPasteboardGateway(),
        ruleEngine: ClipboardRuleEngine = ClipboardRuleEngine(),
        monitorInterval: TimeInterval = 0.5
    ) {
        self.repository = repository
        self.settings = settings
        self.pasteboard = pasteboard
        self.ruleEngine = ruleEngine
        self.monitorInterval = monitorInterval
    }

    func startMonitoring() {
        guard timer == nil else { return }
        lastChangeCount = pasteboard.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: monitorInterval, repeats: true) { [weak self] _ in
            self?.checkForChanges()
        }
    }

    func stopMonitoring() {
        timer?.invalidate()
        timer = nil
    }

    func checkForChanges() {
        let newCount = pasteboard.changeCount
        guard newCount != lastChangeCount else { return }
        let gap = newCount - lastChangeCount
        lastChangeCount = newCount

        if pasteboard.hasMarkerType() {
            NSLog("[ClipMoar] skip: own marker")
            return
        }
        if pasteboard.hasIgnoredSystemType() {
            NSLog("[ClipMoar] skip: ignored system type (transient/auto-generated)")
            return
        }

        if pasteboard.isEmpty() {
            NSLog("[ClipMoar] skip: empty pasteboard")
            if let uuid = lastInsertedUUID {
                repository.removeItem(uuid: uuid)
                lastInsertedUUID = nil
            }
            return
        }

        let sourceAppBundleId = pasteboard.frontmostBundleId
        NSLog("[ClipMoar] new copy from: %@ storeText=%d storeImages=%d", sourceAppBundleId ?? "unknown", settings.storeText ? 1 : 0, settings.storeImages ? 1 : 0)

        if let urls = pasteboard.fileURLs() {
            let paths = urls.map { $0.path }.joined(separator: "\n")
            let fingerprint = ContentFingerprint.hash(text: "file:" + paths)
            guard !handleDuplicate(fingerprint: fingerprint, gap: gap) else {
                NSLog("[ClipMoar] skip: duplicate file")
                return
            }

            lastInsertedUUID = repository.insertFile(paths, sourceAppBundleId: sourceAppBundleId, fingerprint: fingerprint)
            NSLog("[ClipMoar] inserted file: %@", paths)

        } else if settings.storeText, let string = pasteboard.stringValue(), !string.isEmpty {
            let result = ruleEngine.apply(to: string, sourceAppBundleId: sourceAppBundleId)

            if result.text != string {
                NSLog("[ClipMoar] text transformed, writing back to clipboard")
                writeTransformedText(result.text)
            }

            let fingerprint = ContentFingerprint.hash(text: result.text)
            guard !handleDuplicate(fingerprint: fingerprint, gap: gap) else {
                NSLog("[ClipMoar] skip: duplicate text (transform still applied)")
                return
            }

            let appliedRule = result.appliedRules.isEmpty ? nil : result.appliedRules.joined(separator: ", ")
            lastInsertedUUID = repository.insertText(result.text, sourceAppBundleId: sourceAppBundleId, fingerprint: fingerprint, appliedRule: appliedRule)
            NSLog("[ClipMoar] inserted text (rule: %@): %@", appliedRule ?? "none", String(result.text.prefix(80)))

        } else if settings.storeImages, let imageData = pasteboard.imageData() {
            let fingerprint = ContentFingerprint.hash(data: imageData)
            guard !handleDuplicate(fingerprint: fingerprint, gap: gap) else {
                NSLog("[ClipMoar] skip: duplicate image")
                return
            }

            lastInsertedUUID = repository.insertImage(imageData, sourceAppBundleId: sourceAppBundleId, fingerprint: fingerprint)
            NSLog("[ClipMoar] inserted image: %d bytes", imageData.count)
        } else {
            NSLog("[ClipMoar] skip: no matching content (storeText=%d hasString=%d hasImage=%d)", settings.storeText ? 1 : 0, pasteboard.stringValue() != nil ? 1 : 0, pasteboard.imageData() != nil ? 1 : 0)
        }

        repository.trimHistory(maxSize: max(settings.maxHistorySize, 1))
        cleanupOldItems()
    }

    private func handleDuplicate(fingerprint: String, gap: Int) -> Bool {
        guard repository.isDuplicate(fingerprint: fingerprint) else { return false }
        if gap > 1, let uuid = lastInsertedUUID {
            repository.removeItem(uuid: uuid)
            lastInsertedUUID = nil
        }
        return true
    }

    private func writeTransformedText(_ text: String) {
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(text, forType: .string)
        pb.setData(Data(), forType: ClipboardActionService.markerType)
        lastChangeCount = pb.changeCount
    }

    private func cleanupOldItems() {
        repository.removeOlderThan(hours: settings.textRetentionHours, contentType: ClipboardItemType.text.rawValue)
        repository.removeOlderThan(hours: settings.textRetentionHours, contentType: ClipboardItemType.file.rawValue)
        repository.removeOlderThan(hours: settings.imageRetentionHours, contentType: ClipboardItemType.image.rawValue)
    }
}
